export default [
    {
        label:'用户权限',
        icon:'am-icon-table',
        children:[
            {label:'人员管理',path:'/index/manage/person'},
            {label:'群组管理',path:'/index/manage/group'},
            {label:'菜单管理',path:'/index/manage/menu'}
        ]
    },
    {
        label:'课程收费',
        icon:'am-icon-table',
        children:[
            {label:'计费管理',path:'/index/manage/charging'}
        ]
    },
    {
        label:'学生学习情况',
        icon:'am-icon-table',
        children:[
            {label:'成绩管理',path:'/index/manage/charging'},
            {label:'学习统计',path:'/index/manage/statistics'}
        ]
    },
    {
        label:'课程资源',
        icon:'am-icon-table',
        children:[
            {label:'课程管理',path:'/index/course/courseManage'},
            {label:'资源管理',path:'/index/course/resourceManage'}
        ]
    },
    {
        label:'教学管理',
        icon:'am-icon-table',
        children:[
            {label:'学期管理',path:'/index/course/term'},
            {label:'课程计划管理',path:'/index/course/teachTackManage'},
            {label:'课程计划维护',path:'/index/course/teachTackMaintain'},
            {label:'课程作业管理',path:'/index/homework/homeworkManage'},
            {label:'课程实践管理',path:'/index/homework/activityManage'},
        ]
    },
    {
        label:'考试管理',
        icon:'am-icon-table',
        children:[
            {label:'在线考试',path:'/index/exam/examManage'},
            {label:'在线练习',path:'/index/exam/practiceManage'},
            {label:'题库管理',path:'/index/exam/questionManage'},
        ]
    },
    {
        label:'成绩管理',
        icon:'am-icon-table',
        children:[
            {label:'成绩管理',path:'/index/statistics/charging'}
        ]
    },
    {
        label:'讲座研讨',
        icon:'am-icon-table',
        children:[
            {label:'讲座研讨管理',path:'/index/lecture/manage'},
            {label:'报名审核',path:'/index/lecture/entry'},
            {label:'签到管理',path:'/index/lecture/attendance'}
        ]
    },
    {
        label:'课程中心',
        icon:'am-icon-table',
        children:[
            {label:'在线课程',path:'/index/course/coursePreview'},
            {label:'讲座报告',path:'/index/course/lecturePreview'},
            {label:'重要会议',path:'/index/course/meetingPreview'}
        ]
    },
    {
        label:'讲座研讨中心',
        icon:'am-icon-table',
        children:[
            {label:'讲座预览',path:'/index/lecture/lecturePreview'},
            {label:'课程研讨预览',path:'/index/lecture/discussPreview'}
        ]
    },
    {
        label:'我的课程',
        icon:'am-icon-table',
        children:[
            {label:'课程学习',path:'/index/course/courseStudy'},
            {label:'课程作业',path:'/index/homework/unfinished'},
            {label:'课程实践',path:'/index/homework/activityPreview'},
            {label:'已完成课程',path:''}
        ]
    },
    {
        label:'我的考试',
        icon:'am-icon-table',
        children:[
            {label:'待完成考试',path:'/index/exam/unfinishedExam'},
            {label:'已完成考试',path:'/index/exam/finishedExam'},
        ]
    },
    {
        label:'我的讲座研讨',
        icon:'am-icon-table',
        children:[
            {label:'已报名讲座研讨',path:'/index/lecture/entried'},
            {label:'讲座直播',path:'/index/lecture/live'},
            {label:'已完成讲座研讨',path:'/index/lecture/finish'},
        ]
    },
    {
        label:'我的学习统计',
        icon:'am-icon-table',
        children:[
            {label:'学习成果',path:''},
            {label:'课程成绩',path:''},
        ]
    },
]
